### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by kubotaetsuya** [kubotaetsuya/protospace-31640#1]
#URL
 https://protospace-31640.herokuapp.com/

**Comment by genki-inoue-div** [comment]
久保田さん！
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉

大変お疲れさまでした！
ついに最終課題ですね！！

別途、最終課題の案内をチャンネルの方に送信させて頂きます。
今しばらくお待ちください。
